frase = str(input('Digite uma frase:')).strip().upper()
print(f'A letra A aparece {frase.count("A")} vezes na frase')
print(f'A letra E aparece {frase.count("E")} vezes na frase')
print(f'A letra I aparece {frase.count("I")} vezes na frase')
print(f'A letra O aparece {frase.count("O")} vezes na frase')
print(f'A letra U aparece {frase.count("U")} vezes na frase')
print(f'A quantidade de espaços em branco é {frase.count(" ")}')
