n = input('Digite algo:')
print('O tipo primitivo desse valor é:', type(n))
print('É alfábetico?', n.isalpha())
print('Está capitalizada?', n.istitle())
print('É maiúscula?', n.isupper())
print('É alfanumérico?', n.isalnum())
print('É um número?', n.isnumeric())
print('Só tem espaços?', n.isspace())
print('É minúscula?', n.islower())
